spring.application.name=order-management-api
spring.datasource.url=jdbc:postgresql://localhost:5432/order_management_db
spring.datasource.username=postgres
spring.datasource.password=c7940285C

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true=
server.port=8080